### ISSUE TITLE
More examples (maybe copypaste from PM developers portal?)

### ISSUE THREAD

**Issue by pquerner** [repat/plentymarkets-rest-client#1]
I'm new to plentymarkets and havent even started reading their docs yet, but what I always do first is search on github if theres a little snippet which makes it easier to use someones API. 
This neat little thing seems like it does just that, or do I get it wrong?

As I understand plentymarkets, your "item" is like a product with some attributes (and category relation). Would it be possible to add some very basic examples somewhere?

Also, other than Guzzles exceptions, is there a reason you dont fish for specific errors beforehand, or better just pass them along to the users of this project must implement it properly (instead of, again without trying it out, relying on Guzzle and analysing guzzles exception for information).

Thanks!

**Comment by repat** [comment]
Hi Pascal,

thanks for your message.

> This neat little thing seems like it does just that, or do I get it wrong?

That was my goal.

> Would it be possible to add some very basic examples somewhere?

I actually have never tried creating items via SOAP or REST API but used CSV files that fell out of our MySQL database and the Dynamic Importtool. The docs on the files are quite easy to understand. I suggest you read and understand the Plentymarkets item structure before starting anything programming related. You find the manual here: https://www.plentymarkets.eu/handbuch/datenaustausch/datenformate/item/

> Also, other than Guzzles exceptions, is there a reason you dont fish for specific errors beforehand

No, not really. I haven't implemented error handling properly yet. You're welcome to write a pull request because I'm quite occupied with other things at the moment.

**Comment by pquerner** [comment]
Hi repat,

thanks for getting back to me.

I will try to understand the docs beforehand. If I get anything done and I'm sure I'll be using your project here as a base, I will provide PRs if I find something worth upgrading.

-Pascal

**Comment by repat** [comment]
Hi Pascal,

cool, thanks :)

Also, I can recommend to read forum.plentymarkets.com and search for errors there, it's been proven useful a couple of times now. You need a plentymarkets account for that though. A lot of the stuff is still only available via SOAP but it's getting there.
